name: quantum-oracles
channels: 
        - conda-forge
dependencies:
        - pip
        - python=3.8.15
        - pip:
          - jupyterlab
          - matplotlib
          - numpy
          - qiskit==1.0.0
          - pylatexenc
          - qiskit-aer
          - pandas
          - qiskit-algorithms
          - tqdm
          - ipywidgets
          - python-dotenv
          - qiskit-ibm-provider
          - seaborn
          - qiskit-ibm-runtime
